export const SPACE_FRAME_SYSTEM_IDS = [
  "decayVisuals",
  "bg",
  "particles",
  "stations",
  "entities",
  "player",
  "trails",
  "planets",
  "celestial",
  "combat",
  "effects",
  "asteroids",
  "hiteffects",
  "tutmarkers",
  "borders",
  "tuttrack",
  "tutgates",
  "stoverlays",
  "stturrets",
  "lensflare",
  "dmgflash",
  "shockwaves",
  "floattexts",
  "chat",
  "worldborder",
  "crosshair",
  "map",
  "thrust",
  "hud",
  "tarrows",
  "guidearrow",
  "vignette",
  "collisionDebug",
  "renderPixi",
  "mapoverlays",
  "minimap",
  "warpscreen",
] as const;

export type SpaceFrameSystemId = (typeof SPACE_FRAME_SYSTEM_IDS)[number];
