export const ECONOMY = {
  WRECK: {
    despawnSeconds: 300,
    pieceDespawnSeconds: 240,
    pickupLifeSeconds: 120,
    pickupRange: 38,
  },
  SALVAGE: {
    intactPartBaseChance: 0.45,
    intactPartExtraChance: 0.3,
    moduleDropBaseChance: 0.07,
    moduleDropRollBonusMultiplier: 0.4,
  },
  LOOT: {
    intactPartChance: 0.15,
    intactPartQtyMax: 2,
  },
  CREDITS: {
    wreckSplitRatio: 0.4,
    scatterMaxPickups: 4,
    scatterMinPickups: 1,
    scatterPerPickupFloor: 3,
  },
  WRECK_PIECE: {
    baseHp: 28,
    hpPerSigRadius: 0.85,
    baseSpeed: 70,
    speedPerSigRadius: 1.2,
    speedVariationMin: 0.7,
    speedVariationMax: 0.6,
    tangentialScatterMultiplier: 0.4,
    velocityInheritance: 0.4,
    angularVelMax: 5.5,
    angleVariation: 0.6,
  },
  EXPLOSION: {
    sparksBase: 14,
    sparksPerSigRadius: 0.4,
    speedMin: 60,
    speedMax: 220,
    radiusMin: 1,
    radiusMax: 2,
    lifeMin: 0.6,
    lifeMax: 0.5,
    drag: 0.92,
    decay: 1.4,
    shockwaveRadiusBase: 50,
    shockwaveRadiusPerSigRadius: 1.4,
    shockwaveLife: 0.55,
    shockwaveWidth: 2.5,
  },
  PIECE_DESTRUCTION: {
    sparks: 10,
    speedMin: 40,
    speedMax: 140,
    velocityInheritance: 0.3,
    radiusMin: 1,
    radiusMax: 1.6,
    lifeMin: 0.4,
    lifeMax: 0.4,
    drag: 0.93,
    decay: 1.6,
    shockwaveRadius: 28,
    shockwaveLife: 0.35,
    shockwaveWidth: 2,
  },
  SALVAGE_PICKUP: {
    speedMin: 30,
    speedMax: 60,
    velocityInheritance: 0.3,
    bobRate: 3.0,
  },
  CREDIT_PICKUP: {
    scatterVelocityInheritance: 0.2,
    scatterSpeedMin: 20,
    scatterSpeedMax: 40,
    scatterDistanceMin: 25,
    scatterDistanceMax: 55,
    lootVelocityInheritance: 0.3,
    lootSpeedMin: 50,
    lootSpeedMax: 90,
  },
};
