export const PHYSICS = {
  SHIP: {
    lateralThrustScale: 0.55,
    minSpeedForThrust: 12,
    turnRateMultiplier: 2.5,
    brakeVelocityRetention: 0.99,
    brakeAngularRetention: 0.95,
    thrustTrailRearDist: 22,
    thrustTrailNormalColor: "#9ad6ff",
    thrustTrailNormalWidth: 10,
    thrustTrailABColor: "#ffaa55",
    thrustTrailABWidth: 14,
    thrustTrailLife: 0.9,
  },
  COLLISION: {
    restitution: 0.28,
    dmgThreshold: 70,
    dmgScale: 0.055,
    cooldown: 0.35,
    wreckPieceMassMultiplier: 0.8,
    enemyDmgScaleMultiplier: 0.5,
    wreckPieceDmgScaleMultiplier: 0.4,
  },
  DRAG: {
    asteroidVelDecay: 0.12,
    wreckPieceLinear: 0.42,
    wreckPieceAngular: 0.55,
    salvagePickup: 0.55,
    enemyAmbient: 0.04,
    asteroidSpinRange: 0.4,
  },
  MASS: {
    player: 800,
    enemy: 450,
    asteroidDensity: 1.8,
    shipReference: 680000,
  },
  MODULE: {
    hpMax: 100,
    damageChance: 0.4,
    damageRatio: 0.25,
    minThrustPct: 0.3,
  },
  STATION_TURRET: {
    orbitMin: 140,
    orbitMax: 200,
    range: 500,
    damage: 12,
    reload: 1.5,
    alignTolerance: 0.26,
  },
  SPAWN_GRID: {
    cellSize: 128,
  },
};
