export const TARGETING = {
  SENSOR: {
    baseRangePx: 620,
    referenceKm: 72,
    dropRangeMultiplier: 1.08,
  },
  ENEMY_LEVEL: {
    hpScoreMin: 25,
    hpScoreRange: 155,
    dmgScoreMin: 4,
    dmgScoreRange: 30,
    accScoreMin: 0.7,
    accScoreRange: 0.45,
    aggroScoreMin: 260,
    aggroScoreRange: 260,
    spdScoreMax: 180,
    hpWeight: 0.35,
    dmgWeight: 0.30,
    accWeight: 0.20,
    aggroWeight: 0.10,
    spdWeight: 0.05,
    levelMin: 1,
    levelMax: 10,
    levelScale: 9,
    levelOffset: 1,
  },
};
