export const TARGETING = {
  LOCK: {
    baseRangePx: 620,
    referenceKm: 72,
    timeBase: 5.0,
    sigReference: 38,
    sigExponent: 0.9,
    multFloor: 0.42,
  },
  SENSOR: {
    baseRangePx: 620,
    referenceKm: 72,
    dropRangeMultiplier: 1.08,
  },
  ASTEROID_LOCK_TIME: 1.4,
  WRECK_PIECE_LOCK_TIME: 0.9,
  MAX_TARGET_LOCKS_BASE: 2,
  MAX_TARGET_LOCKS_CAP: 9,
  ENEMY_LEVEL: {
    hpScoreMin: 25,
    hpScoreRange: 155,
    dmgScoreMin: 4,
    dmgScoreRange: 30,
    accScoreMin: 0.7,
    accScoreRange: 0.45,
    aggroScoreMin: 260,
    aggroScoreRange: 260,
    spdScoreMax: 180,
    hpWeight: 0.35,
    dmgWeight: 0.30,
    accWeight: 0.20,
    aggroWeight: 0.10,
    spdWeight: 0.05,
    levelMin: 1,
    levelMax: 10,
    levelScale: 9,
    levelOffset: 1,
  },
};
